# Generated by Django 5.2.3 on 2025-11-06 08:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('site_id', models.IntegerField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=255)),
                ('site_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'site',
            },
        ),
        migrations.CreateModel(
            name='NameString',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'string_name',
            },
        ),
        migrations.CreateModel(
            name='SolarSystemData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('irradiance', models.FloatField()),
                ('active_power', models.FloatField()),
                ('temp', models.FloatField()),
            ],
            options={
                'db_table': 'solardb',
            },
        ),

        migrations.CreateModel(
            name='Inverter',
            fields=[
                ('inverter_id', models.IntegerField(primary_key=True, serialize=False)),
                ('inverter_name', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('serial_number', models.CharField(max_length=50)),
                ('system_diagram', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('capacity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('string_current', models.DecimalField(decimal_places=2, max_digits=10)),
                ('active_power', models.DecimalField(decimal_places=2, max_digits=10)),
                ('input_power', models.DecimalField(decimal_places=2, max_digits=10)),
                ('apparent_power', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reactive_power', models.DecimalField(decimal_places=2, max_digits=10)),
                ('power_factor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('grid_frequency', models.DecimalField(decimal_places=2, max_digits=10)),
                ('internal_temp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('a_phase_current', models.DecimalField(decimal_places=2, max_digits=10)),
                ('b_phase_current', models.DecimalField(decimal_places=2, max_digits=10)),
                ('c_phase_current', models.DecimalField(decimal_places=2, max_digits=10)),
                ('a_phase_voltage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('b_phase_voltage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('c_phase_voltage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('line_voltage_L1_L2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('line_voltage_L2_L3', models.DecimalField(decimal_places=2, max_digits=10)),
                ('line_voltage_L3_L1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('production', models.DecimalField(decimal_places=2, max_digits=10)),
                ('irradiance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('irradiation', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.site')),
            ],
            options={
                'db_table': 'inverter',
            },
        ),
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('meter_id', models.IntegerField(primary_key=True, serialize=False)),
                ('meter_name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=20)),
                ('attribute', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('active_generated', models.DecimalField(decimal_places=2, max_digits=10)),
                ('active_consumed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reactive_generated', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reactive_consumed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('production', models.DecimalField(decimal_places=2, max_digits=10)),
                ('irradiance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'meter',
            },
        ),
        
        migrations.CreateModel(
            name='Weather_station',
            fields=[
                ('weather_station_id', models.IntegerField(primary_key=True, serialize=False)),
                ('weather_station_name', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=20)),
                ('irradiation', models.DecimalField(decimal_places=2, max_digits=15)),
                ('poa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ghi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('wind_speed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('wind_direction', models.CharField(max_length=20)),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rainfall', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ambient_temp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('module_temp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'weather_station',
            },
        ),
        
        migrations.CreateModel(
            name='StringSolarData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('yields', models.FloatField()),
                ('production', models.FloatField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.namestring')),
            ],
            options={
                'db_table': 'string_data',
            },
        ),
    ]
