# Generated by Django 5.2.3 on 2025-11-07 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meter',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='weather_station',
            options={'managed': False},
        ),
    ]
