# Generated by Django 5.2.3 on 2025-11-09 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_meter_site_site_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weather_station',
            options={},
        ),
    ]
