# Generated by Django 5.2.3 on 2025-11-09 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_alter_weather_station_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather_station',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data.site'),
            preserve_default=False,
        ),
    ]
