# Generated by Django 5.2.3 on 2026-04-18 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_alter_meter_active_consumed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meter',
            old_name='active_consumed',
            new_name='apparent_power_l1',
        ),
        migrations.RenameField(
            model_name='meter',
            old_name='active_generated',
            new_name='current_l1',
        ),
        migrations.RenameField(
            model_name='meter',
            old_name='irradiance',
            new_name='current_l1_dmd',
        ),
        migrations.RenameField(
            model_name='meter',
            old_name='production',
            new_name='frequency_l1',
        ),
        migrations.RenameField(
            model_name='meter',
            old_name='reactive_consumed',
            new_name='real_power',
        ),
        migrations.RenameField(
            model_name='meter',
            old_name='state',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='meter',
            old_name='reactive_generated',
            new_name='voltage_l1',
        ),
        migrations.RemoveField(
            model_name='meter',
            name='type',
        ),
        migrations.AddField(
            model_name='meter',
            name='device_model',
            field=models.CharField(default='em-07k', max_length=255),
            preserve_default=False,
        ),
    ]
