# Generated by Django 5.2.3 on 2026-04-18 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_rename_active_consumed_meter_apparent_power_l1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meter',
            old_name='site',
            new_name='site_id',
        ),
    ]
