# Generated by Django 5.2.3 on 2026-04-27 04:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_rename_site_meter_site_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_address', models.IntegerField(blank=True, null=True)),
                ('register_name', models.CharField(db_index=True, max_length=255)),
                ('value', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
                ('received_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registers', to='data.meter')),
            ],
            options={
                'db_table': 'meter_register',
                'indexes': [models.Index(fields=['meter', 'received_at'], name='meter_regis_meter_i_83a5f4_idx')],
            },
        ),
    ]
