# Generated by Django 5.2.3 on 2026-05-01 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_meterregister'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='gateway_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
