# Generated by Django 5.2.3 on 2026-05-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_site_gateway_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='site_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
