# Generated by Django 5.2.3 on 2026-05-07 04:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_alter_site_site_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('severity', models.CharField(choices=[('ok', 'OK'), ('warning', 'Warning')], default='ok', max_length=10)),
                ('wire_p1_ok', models.BooleanField(default=False)),
                ('wire_p2_ok', models.BooleanField(default=False)),
                ('active_port', models.IntegerField(default=0)),
                ('total_devices', models.IntegerField(default=0)),
                ('active_count', models.IntegerField(default=0)),
                ('inactive_count', models.IntegerField(default=0)),
                ('site', models.ForeignKey(db_column='site_id', on_delete=django.db.models.deletion.CASCADE, related_name='scan_results', to='data.site')),
            ],
            options={
                'db_table': 'scan_result',
                'ordering': ['-scanned_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modbus_id', models.IntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('scan_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='data.scanresult')),
            ],
            options={
                'db_table': 'scan_device',
            },
        ),
        migrations.AddIndex(
            model_name='scanresult',
            index=models.Index(fields=['site', 'scanned_at'], name='scan_result_site_id_c6f9e8_idx'),
        ),
        migrations.AddIndex(
            model_name='scandevice',
            index=models.Index(fields=['scan_result', 'status'], name='scan_device_scan_re_2414b1_idx'),
        ),
    ]
