# Generated by Django 5.2.3 on 2026-05-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_scanresult_scandevice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanresult',
            name='final_id_p1',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='final_id_p2',
            field=models.IntegerField(default=0),
        ),
    ]
