# Generated by Django 5.2.3 on 2026-05-17 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_scanresult_final_id_p1_scanresult_final_id_p2'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanresult',
            name='dual_port_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='line_ok',
            field=models.BooleanField(default=True),
        ),
    ]
