# Generated by Django 5.2.3 on 2026-06-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_scanresult_dual_port_mode_scanresult_line_ok'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
